// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC1t0OoB5UOQQHtvxszPe3536VtwhTZQo',
    appId: '1:295155873880:web:970767da495588ec5db22d',
    messagingSenderId: '295155873880',
    projectId: 'geminiai-app',
    authDomain: 'geminiai-app.firebaseapp.com',
    storageBucket: 'geminiai-app.appspot.com',
    measurementId: 'G-4P397WMCY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw42Lt7wks73iHFffL8v_kMDURUBsaJkQ',
    appId: '1:295155873880:android:7afee5b3ba187ae05db22d',
    messagingSenderId: '295155873880',
    projectId: 'geminiai-app',
    storageBucket: 'geminiai-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs5oA3vbgfh65qjJWbIQKBd82TEUpiYO4',
    appId: '1:295155873880:ios:abda87bb90c99a655db22d',
    messagingSenderId: '295155873880',
    projectId: 'geminiai-app',
    storageBucket: 'geminiai-app.appspot.com',
    iosBundleId: 'com.example.geminiAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs5oA3vbgfh65qjJWbIQKBd82TEUpiYO4',
    appId: '1:295155873880:ios:d75db10ad5b6ae0c5db22d',
    messagingSenderId: '295155873880',
    projectId: 'geminiai-app',
    storageBucket: 'geminiai-app.appspot.com',
    iosBundleId: 'com.example.geminiAi.RunnerTests',
  );
}
